#!/usr/bin/env python

from sys import argv, exit, stdin

to_check = {};
f = open(argv[1]);
lines = f.readlines();
for line in lines:
    tokens = line.split();
    if len(tokens) > 1:
        if tokens[0] == "//" and tokens[1] == "CHECK":
            to_check[tokens[2]] = tokens[3];
f.close();

lines = stdin.readlines();
start = False;
for line in lines:
    if line[0:8] == "[Result]":
        start = True;
    if start:
        tokens = line.strip("\n").partition(":");
        if tokens[1] != "":
            left = tokens[0].strip(" ");
            idx = left.rfind("(");
            if idx == -1:
                idx = tokens[0].rfind(" ");
                idx = idx + 1;
            name = left[idx:];
            right = tokens[2].strip(" ");
            if name in to_check:
                if to_check[name] != right:
                    print name + " mismatch:";
                    print "expect: " + to_check[name];
                    print "got: " + right;
                    exit(1);
                else:
                    del to_check[name];

for k in to_check.keys():
    print k + " missing";
    print "expect: " + to_check[k];
    exit(1);
